// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // prisma CLI (db push/migrate) ต้องใช้สายตรง 5432 — transaction pooler 6543 ทำ CLI ค้าง (ดู PROGRESS.md)
    // รัน CLI ด้วย: PRISMA_CLI_DIRECT=1 npx prisma db push · runtime ปกติใช้ pooler ตามเดิม
    url: process.env["PRISMA_CLI_DIRECT"]
      ? process.env["DIRECT_URL"]
      : process.env["DATABASE_URL"],
  },
});
